### ISSUE TITLE
HDFS instance must be "shared"

### ISSUE THREAD

**Issue by iman-saleh** [trustedanalytics/dataset-reader-sample#2]
The following steps need to be updated to clearly specify that the HDFS instance needs to be a "shared" instance. Otherwise, the application won't run:

Using WebUI:
Go to Marketplace
Select HDFS service offering
Type the name of the instance: hdfs-instance (Note: the instance must be called hdfs-instance)
Click Create new instance

**Comment by szymonbultrowicz** [comment]
Information about service plan has been added to README.
